version: '2.1'
services:
  #Besu 1
  node1:
    user: root
    container_name: besu-nodes-1
    volumes:
      - ./node1:/var/lib/node
      - ./common:/var/lib/besu
      - ./orion/node1/node1Key.pub:/var/lib/orion/node1Key.pub
    image: hyperledger/besu:latest
    command:
      --config-file=/var/lib/besu/config.toml
      --network-id 123
      --bootnodes="enode://7067e3ba6f10d0745afebcdf5fa5edad70334b2612a7a21bb040b3b93f7eea345bd50adbf8cd4697b7f49e77de3dd961fe92bcd079d3c03da5efc3c19890c996@172.16.1.33:30000"
      --p2p-host=172.16.1.30
      --privacy-enabled=true
      --privacy-url=http://172.16.1.51:8880
      --privacy-public-key-file=/var/lib/orion/node1Key.pub
    ports:
      - "8545:8545"
      - "8546:8549"
    networks:
      besu:
        ipv4_address: 172.16.1.30


  #Besu 2
  node2:
    container_name: besu-nodes-2
    volumes:
      - ./node2:/var/lib/node
      - ./common:/var/lib/besu
      - ./orion/node2/node2Key.pub:/var/lib/orion/node2Key.pub
      - ./data:/opt/besu/database
    image: hyperledger/besu:latest
    command:
      --config-file=/var/lib/besu/config.toml
      --network-id 123
      --bootnodes="enode://7067e3ba6f10d0745afebcdf5fa5edad70334b2612a7a21bb040b3b93f7eea345bd50adbf8cd4697b7f49e77de3dd961fe92bcd079d3c03da5efc3c19890c996@172.16.1.33:30000"
      --privacy-enabled=true
      --privacy-url=http://172.16.1.52:8880
      --privacy-public-key-file=/var/lib/orion/node2Key.pub
    ports:
      - "8547:8545"
    networks:
      besu:
        ipv4_address: 172.16.1.31

  #Besu 3
  node3:
    container_name: besu-nodes-3
    volumes:
      - ./node3:/var/lib/node
      - ./common:/var/lib/besu
      - ./orion/node3/node3Key.pub:/var/lib/orion/node3Key.pub
    image: hyperledger/besu:latest
    command:
      --config-file=/var/lib/besu/config.toml
      --network-id 123
      --bootnodes="enode://7067e3ba6f10d0745afebcdf5fa5edad70334b2612a7a21bb040b3b93f7eea345bd50adbf8cd4697b7f49e77de3dd961fe92bcd079d3c03da5efc3c19890c996@172.16.1.33:30000"
      --privacy-enabled=true
      --privacy-url=http://172.16.1.53:8880
      --privacy-public-key-file=/var/lib/orion/node3Key.pub
    ports:
      - "8548:8545"
    networks:
      besu:
        ipv4_address: 172.16.1.32

  #Besu 4
  node4:
    container_name: besu-nodes-4
    volumes:
      - ./node4:/var/lib/node
      - ./common:/var/lib/besu
    image: hyperledger/besu:latest
    command:
      --config-file=/var/lib/besu/config.toml
      --network-id 123
    networks:
      besu:
        ipv4_address: 172.16.1.33
    restart: always
    ports:
      - "30000:30000"

  explorer :
    container_name: eplorer-node
    image : alethio/ethereum-lite-explorer
    env_file:
      - ./vars.env
    ports:
      - "20000:80"
    networks:
      besu:
        ipv4_address: 172.16.1.34

# Network
networks:
  besu:
    external:
      name: orion_besu
